### ISSUE TITLE
Installations

### ISSUE THREAD

**Issue by nfc456** [PatWie/CppNumericalSolvers#38]
I tried to install the CppNumericalSolvers in our linux service. However, I am confused about the step of adjusting paths and compiler (supports g++, clang++). If we do not have the Matlab, whether can I install the library? Grateful if you can give a detailed description of the CppNumericalSolvers.config file.

**Comment by PatWie** [comment]
I will repy with more details in another comment (due to a lack of time). But for now this should help:
You should git clone this repo recursive to get the gtest submodul. Next, this project needs a recent version of cmake and gtest to avoid an infinite loop during compilation.
All necessary steps are described in the travis.yml file (provided by @spinicist ).

CppNumericalSolvers.config can be (and should be) an empty file.

**Comment by nfc456** [comment]
Sorry, I feel confused. How can I get the gtest submodul?

**Comment by PatWie** [comment]
This works for me:

Remember, that this is a header-only library. So you do not need to compile or install anything at all. Simply put the lib somewhere and include the header.

The installation is only for the unit_tests

```
git clone --recursive https://github.com/PatWie/CppNumericalSolvers.git
cd CppNumericalSolvers/
touch CppNumericalSolvers.config
mkdir build
cd build
cmake ..
make all
./bin/verify
```

And everything should be OK.
