### ISSUE TITLE
CMAES failed

### ISSUE THREAD

**Issue by PatWie** [PatWie/CppNumericalSolvers#58]
There are now 2 test-cases which do not work

```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] CMAesTest.RosenbrockFarValue
[  FAILED  ] CMAesTest/0.RosenbrockFarFull, where TypeParam = float
```

**Comment by spinicist** [comment]
Far does fail sometimes, but passes most of the time (on my system at least) due to its stochastic nature. The solver should have failed these tests before - it was ignoring the starting point and generating a new one that was close to the solution, so was never actually testing the Far/Mix conditions.

The CMAes needs work to make it more robust, but unfortunately I am very busy with other stuff at the moment.

**Comment by PatWie** [comment]
@spinicist 
For fixing the matlab binding I had to remove the CMAES solver. Do you know where the issues come from?

**Comment by spinicist** [comment]
Sorry, I have no idea. Work is really busy at the moment so I don't know when I will get a chance to look.
