### ISSUE TITLE
Eigen 3.3.x fails tests

### ISSUE THREAD

**Issue by ryanlevy** [PatWie/CppNumericalSolvers#76]
As seen in #68, the newer version of Eigen has an extra catch for using empty matrices. As an explanation of what's going on, the following snippet works under 3.2 but not 3.3
```c
MatrixXd m,v;
std::cout << m.lu().solve(v)<<std::endl;
```
Theoretically, we should be able to change the line [here](https://github.com/PatWie/CppNumericalSolvers/blob/f28155a2975bc9fc397dfbef78f676d6dbe8e7d9/include/cppoptlib/solver/lbfgsbsolver.h#L191) to be something like
```C
if(v.size()!=0) v = N.lu().solve(v); 
```
but two tests still fail:
[  FAILED  ] LbfgsbTest.RosenbrockMixFull
[  FAILED  ] LbfgsbTest/0.RosenbrockFarFull, where TypeParam = float

Something else seems to have broken, at least for the parameters in the verify test.

**Comment by PatWie** [comment]
Now, it should be fairly easy to test multiple Eigen versions using the bazel-build system. I will have a look into this.

**Comment by PatWie** [comment]
This is really an interesting case! Honestly, I don't know what changed in Eigen3.3. The test using float fails, so it might be a numerical issue.

**Comment by spinicist** [comment]
I had a brief look at this today as I finally upgraded Eigen to 3.3.0. The tests run fine on my machine, both for float and double. However, I am very confused by: `https://github.com/PatWie/CppNumericalSolvers/blob/master/include/cppoptlib/solver/lbfgsbsolver.h#L194`

The following Eigen code triggers an assert in debug mode, because the size of the LHS and RHS don't match:
`Eigen::Matrix2d A = Eigen::Matrix2d::Identity();
    Eigen::MatrixXd B;
    Eigen::Vector2d c = Eigen::Vector2d::Ones();
    Eigen::VectorXd d;
    Eigen::VectorXd temp = (1*c - 1*1*B.transpose()*d);`

I think this code should be equivalent to line 194 when the `W` matrix is empty - but line 194 does not trigger the assert!

I am totally confused why line 194 does not trigger the assert. But I don't want to report a bug to Eigen unless I can produce a minimal example.

I think that whole block of code needs refactoring for the case of `W` being empty - but I don't quite follow the algorithm to do it justice.

**Comment by PatWie** [comment]
Seems to be no issue in Eigen 3.3.4 (see #102)
